Update nextjs.yml
got ride of the error

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -20,52 +20,52 @@ concurrency:
   group: "pages"
   cancel-in-progress: false
 
-build:
-  defaults:
-    run:
-      working-directory: ./client
+defaults:
+  run:
+    working-directory: ./client
 jobs:
+  build:
     runs-on: ubuntu-latest
-    # Build job
+      # Build job
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           path: client
-
-      # - name: Detect package manager
-      #   id: detect-package-manager
-      #   run: |
-      #     if [ -f "client/bun.lockb" ]; then
-      #       echo "manager=bun" >> $GITHUB_ENV
-      #       echo "command=install" >> $GITHUB_ENV
-      #       echo "runner=bunx" >> $GITHUB_ENV
-      #     elif [ -f "client/package.json" ]; then
-      #       echo "manager=bun" >> $GITHUB_ENV
-      #       echo "command=ci" >> $GITHUB_ENV
-      #       echo "runner=bunx --no-install" >> $GITHUB_ENV
-      #     else
-      #       echo "Unable to determine package manager"
-      #       exit 1
-      #     fi
-
+  
+        # - name: Detect package manager
+        #   id: detect-package-manager
+        #   run: |
+        #     if [ -f "client/bun.lockb" ]; then
+        #       echo "manager=bun" >> $GITHUB_ENV
+        #       echo "command=install" >> $GITHUB_ENV
+        #       echo "runner=bunx" >> $GITHUB_ENV
+        #     elif [ -f "client/package.json" ]; then
+        #       echo "manager=bun" >> $GITHUB_ENV
+        #       echo "command=ci" >> $GITHUB_ENV
+        #       echo "runner=bunx --no-install" >> $GITHUB_ENV
+        #     else
+        #       echo "Unable to determine package manager"
+        #       exit 1
+        #     fi
+  
       - name: Set package manager to bun
         id: set-package-manager-to-bun
         run: |
           echo "manager=bun" >> $GITHUB_ENV
           echo "command=install" >> $GITHUB_ENV
           echo "runner=bunx" >> $GITHUB_ENV
-
+  
       - name: Setup Bun
         uses: oven-sh/setup-bun@v1
         with:
           bun-version: latest
-
+  
       - name: Setup Pages
         uses: actions/configure-pages@v3
         with:
           static_site_generator: next
-
+  
       - name: Restore cache
         uses: actions/cache@v3
         with:
@@ -78,18 +78,18 @@ jobs:
           # If source files changed but packages didn't, rebuild from a prior cache.
           restore-keys: |
             ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-
-
+  
       - name: Install dependencies
         run: |
           cd client
           ${{ env.manager }} ${{ env.command }}
-
+  
       - name: Build with Next.js
         run: |
           cd client
           mkdir out
           ${{ env.manager }} next build
-
+  
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
@@ -97,7 +97,6 @@ jobs:
           path: out
           if-no-files-found: error
 
-  # Deployment job
   deploy:
     environment:
       name: github-pages
